server:
  port: 8087
  baseUrl: http://localhost:8087

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver

odm:
  product-plane:
    policy-service:
      active: true
      address: http://localhost:8005
      version: 1
